releases:
  - name: mysql
    chart: stable/mysql
    values:
      - mysqlUser: "kinkyapi"
        mysqlPassword: {{ requiredEnv "MYSQL_PASS" }}
        mysqlDatabase: "kinkyapi"
          

  - name: kinkyapi
    chart: ./helm
    values:
      - image:
          repository: somerepo
          tag: latest
        imagePullSecrets: []
        ingress:
          enabled: true
          hosts:
            - host: kinkyapi.xyz
              paths: ["/"]
          tls:
            - secretName: kinkyapi.xyz
              hosts:
                - kinkyapi.xyz
        env:
          - name: MYSQL_USER
            value: "kinkyapi"
          - name: MYSQL_HOST
            value: "mysql"
          - name: DOMAIN
            value: kinkyapi.xyz
          - name: MYSQL_PASS
            value: {{ requiredEnv "MYSQL_PASS" }}
          - name: SECRET_KEY
            value: {{ requiredEnv "SECRET_KEY" }}
